name: DuoBorgatto
favicon: null
layout_spectrum: 0.980934118386358
typography_spectrum: 0.3489264026284218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3466881869826466
  lightness: 0.7307691285386682
  saturation: 0.6741417394950986
  rhythmicContrast: 0.8244584030471742
purpose: []
